### PR TITLE
Added packages for Mark Post

### PR DESCRIPTION
**Pull request by markkp**

### CODE REVIEW

**Comment by scarabeusiv** [comment]
Could you kindly rationalize it? By default we want latest packages in Tumbleweed.
Also there is OBS attribute so you don't really need to do this.

**Comment by markkp** [comment]
I tried to find documentation for such an attribute, but couldn't find one. If you can point me to that, or just tell me which attribute to set, you can reject this pull request.

**Comment by scarabeusiv** [comment]
To quote the README in this repo:

Disabling autosubmit behavior for a project or a package
========================================================

It's possible to disable the autosubmit behavior for a project or a package via
the openSUSE:DisableAutoSubmit attribute, if it set to true or 1.

This can be achieved with osc:

 osc meta attribute PROJECT [PACKAGE] --attribute openSUSE:DisableAutoSubmit --set true

**Comment by markkp** [comment]
Thanks!

**Comment by plusky** [comment]
I am still curious why you want to disable automatic submissions ...

**Comment by markkp** [comment]
Because I want to use my devel projects for devel, not staging. I don't want to be surprised when a package gets submitted before I'm ready for that to happen.

**Pull request closed without merging**
